# Generated by Django 4.2.10 on 2024-02-28 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_brushing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brushing',
            old_name='meal',
            new_name='brushing',
        ),
    ]
