# Generated by Django 4.2.10 on 2024-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_accessory_alter_brushing_options_alter_brushing_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monkey',
            name='accessories',
            field=models.ManyToManyField(to='main_app.accessory'),
        ),
    ]
